### PR TITLE
Keymaps (sublime,vim,...)

### PR DESCRIPTION
**Pull request by Aslemammad**
I added a keymaps option for people who love vim, emacs, or sublime(the ordinary one). Love.

### CODE REVIEW

**Comment by Aslemammad** [comment]
@kavu

**Comment by mfix22** [comment]
Hi @Aslemammad sorry for the delay. 

Carbon is not meant to replicate other editors—it has entirely separate goals than a code editor does—and therefore we want it to behave differently. 

That said, I might be fine with adding a Vim mode toggle in the Editor menu, as a beta feature, to see if other people are interesting in using it, but we won't support a dropdown list of keybindings.

**Comment by Aslemammad** [comment]
I got that, Thanks for preview mode, I appreciate it.

**Comment by Aslemammad** [comment]
We'll see the users' reactions.

**Comment by Aslemammad** [comment]
Or we can add vim as a checkbox.

**Pull request closed without merging**
