### PR TITLE
[feat-lang]: keep zh-cn tranlation up to date

### PR DESCRIPTION
**Pull request by seognil**

### CODE REVIEW

**Comment by mfix22** [comment]
Thanks so much @seognil 

@kelthuzadx can you give this a _quick_ look and approve?

**Comment by mfix22** [comment]
@seognil while you are here, can you update the badges to match the english README, just like someone did here https://github.com/carbon-app/carbon/pull/917?

**Comment by seognil** [comment]
@mfix22 seems already did that,
I match the English version structure first, then complete the unimproved parts,
contribution section untouched

**Comment by mfix22** [comment]
My bad! Thank you 👍

**Pull request merged**
