### PR TITLE
Upgrade to modern mode and granular chunks

### PR DESCRIPTION
**Pull request by timneutkens**
@prateekbh will be interested in tracking results :+1:

### CODE REVIEW

**Comment by mfix22** [comment]
Getting `CodeMirror is not defined` errors: 
Screenshot 2019-08-18 13 06 55

**Comment by timneutkens** [comment]
@mfix22 aware, already asked @janicklas-ralph to investigate!

**Comment by prateekbh** [comment]
is there already some analytics in place or if you guys like can i add some?

**Comment by janicklas-ralph** [comment]
`type=module` scripts are in strict mode by default. Theres a dependency [codemirror-solidity](https://github.com/alincode/codemirror-solidity) thats adding a global variable.

I've raised a [PR](https://github.com/alincode/codemirror-solidity/pull/1) to fix it. We could just update the version as part of the PR.

**Pull request merged**
