### PR TITLE
Add export to imgur

### LINKED ISSUE #688: Export to imgur
## Introduction

All the export feature are awesome 👍🏻, but when we click on `open` it redirects to blob page and `Copy Embed` gives the iframe for HTML pages.

image

This feature request is the combination of both the features, where users can just paste the image url to the webpage.

## Development process

There can a button which says `Export to imgur`, based on the user selected settings carbon will generate the image, export to imgur and return back the image url which will be copied the clipboard.

## Why Imgur?

[Imgur](https://imgur.com) is most popular place to upload unlimited images for free and **yes, for FREE.** 😂

### Reference

> Send the code & it returns a dynamic image.

[@deadcoder0904](https://github.com/dawnlabs/carbon/issues/210#issue-294718316)

### PR DESCRIPTION
**Pull request by amitkeinan9**
Add support to export the snippet as an image to Imgur using Imgur's API.

Screen Shot 2021-01-13 at 0 44 40
When clicking "Export to imgur" the image will be uploaded to imgur with the given title.

The only thing left to do is to [create an official client id for carbon](https://api.imgur.com/oauth2/addclient) and set it in the `NEXT_IMGUR_CLIENT_ID` environment variable.

Closes  #688

### CODE REVIEW

**Comment by liadyacobi** [comment]
Sweet, pretty useful feature for me

**Review by mfix22 — CHANGES_REQUESTED** [review]
This is pretty neat! If I were to add this, I would like it to be another button included as a drop down below "Tweet" 

Also, if you could run Prettier on your changes, that will make it much easier to review. 

Thanks!

**Comment by adirsiton** [comment]
Sweet feature!

**Comment by amitkeinan9** [comment]
Screen Shot 2021-01-13 at 9 42 50

I've created a new share menu for the two options and also ran Prettier

**Comment by mfix22** [comment]
This is looking good! I'm going to look into some stylistic tweaks before merging.

**Comment by amitkeinan9** [comment]
Are there any more fixes that need to be done?

**Comment by mfix22** [comment]
> Are there any more fixes that need to be done? @mfix22

@amitkeinan9 nope! I don't think so. I haven't had time to test this end-to-end yet. I hope to get to it soon, but have been super busy. 

Testing it with a real Imgur key and posting a video here would speed things up!

**Comment by amitkeinan9** [comment]
https://user-images.githubusercontent.com/16577335/107127985-c1d77880-68c2-11eb-9592-5d8ba46701dd.mov

**Comment by amitkeinan9** [comment]
https://user-images.githubusercontent.com/16577335/107128150-fb5cb380-68c3-11eb-9835-27ea2b0f2498.mov

@mfix22

**Review by mfix22 — APPROVED** [review]

**Pull request merged**
