### PR TITLE
Docs cleanup

### PR DESCRIPTION
**Pull request by timwienk**
Two main things I changed:

- Went through the translated README documents, and changed the structure to match the English README.md.
- Added missing Polish and Swedish files to .all-contributorsrc, and changed the file order to be alphabetic.

Hope it helps other contributors to add missing translations to the README files, when the structure is the same again.

### CODE REVIEW

**Review by mfix22 — CHANGES_REQUESTED** [review]
Hi @timwienk 👋 Sorry for the delay!

Thanks so much for this! I especially appreciate you adding the missing documents to `.all-contributorsrc`

That said, I would appreciate it if you could avoid _changing_ any copy that was written by other translators, unless you are also fluent in that language. I'll let you be the judge of that 🙂 

Would love to merge this PR, but can't without knowing the copy is still "correct"

**Comment by timwienk** [comment]
Hi @mfix22,

I'm not sure there is any delay to speak of when it's only been a few hours.\
So instead I'd like to say thanks for the quick response. :+1:

While I can't say I'm fluent in all languages I updated the files of, I did make sure to not actually _change_ any translations. What I did do is move parts around in the files, so the order in the files is the same as the English README.\
So in short, if the translation was correct before, it still is now.

I was thinking about adding all non-translated parts in English in the translated documents (mostly to make it less effort to translate), but figured that might be confusing for readers. (However - if you think that would help, do let me know.)

In two cases I did add translations:

1. The title "License" in cases where the title was not yet present, which really was easy enough since that word is translated often (I took the translations I used from gettext `msgid "License"` translations from another project).
2. The title "All contributors" in cases where the title was not yet present, and only where I was confident enough about the translation.

In response to your message I changed the first commit slightly (squashed into the first commit): 

- To be sure I did change the "All contributors" text back to English for a few cases of which I am less sure.
- I actually noticed two copy/paste errors for "License".

If you would prefer these additions not made (or just in English), do let me know as well - the goal of this PR is to help, not make things more difficult. I can submit a PR for just the `.all-contributorsrc` change as well of course.

**Comment by timwienk** [comment]
And now it's rebased on top of the updated `main` branch.

**Review by mfix22 — APPROVED** [review]
@timwienk Amazing! The diff made this PR particularly hard to understand, but I see what you have done now. I am happy to keep "All contributors" in English in all places where it hasn't already been translated, as that text is basically a Brand Name. 

I'm going to merge this as is, but if you want to make a follow up with some of the more nuanced translations/changes, that would be much appreciated! 

As always, breaking up changes into smaller chunks are much easier for me to review 🙂 

Thanks so much for tackling this!

**Comment by timwienk** [comment]
> The diff made this PR particularly hard to understand, but I see what you have done now. I am happy to keep "All contributors" in English in all places where it hasn't already been translated, as that text is basically a Brand Name.
> 
> As always, breaking up changes into smaller chunks are much easier for me to review :slightly_smiling_face:

Sorry about that. It's always hard to get it right in a first contribution to a project.

If it were for a project of my own, I would actually have split the commit up in several smaller ones, but I often find people dislike too much splitting up so I bundle it a bit more per "subject" when I submit to a project I don't know well. You may know the feeling. :smile:

It's actually nice having someone tell me the opposite for once, that they like it more split up!

> if you want to make a follow up with some of the more nuanced translations/changes, that would be much appreciated!

I'll focus on what I know best. I'm almost done with a Dutch translation, coming up in a bit.

> Thanks so much for tackling this!

Happy to help. These are not the most fun things to pick up, but I heard you enthusiastically talk about the many translations of the README on [The Changelog #410](https://changelog.com/podcast/410) and figured I could lend a hand. Hopefully it helps getting them more up-to-date again too.

**Comment by mfix22** [comment]
> Edit: And yes, it is indeed fun to see these bots do their work!

LOL 🤣  🙂 

Thanks @timwienk 🙏

**Pull request merged**
