### PR TITLE
upgrade next to fix url errors

### LINKED ISSUE #927: Javascript promise errors in console
I'm getting a lot of Javascript `Promise` errors in the console like the one in the screenshot below. The code snippets are showing correctly, but still the console log errors are annoying. 

image

### LINKED ISSUE #929: Newlines in url stopped working
The following yaml snippet isn't rendered properly

```
abc:
  - line1
  - line2
```

after being converted to url 

```
https://carbon.now.sh/?code=abc%3A%0A%20%20-%20line1%0A%20%20-%20line2%0A
```

2020-01-10 at 16 58

Everything after the first `%0A` character is discarded.  This breaks editor integrations.

### PR DESCRIPTION
**Pull request by mfix22**
Closes #927 
Closes #929

### CODE REVIEW

**Comment by mfix22** [comment]
@Timer https://carbon-git-upgrade-next-to-fix-url-errors.carbon-app.now.sh/embed?l=javascript

Still does not allow use to pass `javascript` as a query param, so we cannot close #927.

**Comment by mfix22** [comment]
https://carbon-git-upgrade-next-to-fix-url-errors.carbon-app.now.sh/?code=abc%3A%0A%20%20-%20line1%0A%20%20-%20line2%0A works, so we can close #929

**Comment by Timer** [comment]
Interesting! Let me look into the javascript one — I'll get back to you. We've completely removed `native-url`, so I'm guessing `javascript` has never worked @mfix22 (and thus it'd be fine to upgrade).

**Comment by Timer** [comment]
Ah, yes @mfix22 see console:
```
main-bf88e3b77ee835f5a8f4.js?__WB_REVISION__=28f27022521b796ed26f:1 Error: URL contains XSS injection attempt
    at o (commons.10b2916fe71e85c990dd.js?__WB_REVISION__=ea53f4f6a1afed6a8aff:1)
    at commons.10b2916fe71e85c990dd.js?__WB_REVISION__=ea53f4f6a1afed6a8aff:1
```

**Comment by mfix22** [comment]
@Timer I thought that was coming from `next`! Could it be coming from Chrome itself?

**Comment by mfix22** [comment]
@Timer turns out it was `axios`, but they reverted that change. 

Thanks for alllllllll the help! 🙂

**Pull request merged**
