### PR TITLE
Optimize PNGs and SVGs

### PR DESCRIPTION
**Pull request by majouji**
## PNGs

PNGs were ran through ImageOptim’s lossless compression and no metadata was stripped. No quality loss - only smaller files!

## SVGs

SVGs were optimized using SVGO CLI `svgo --pretty --indent 2 *.svg`, and some of them were optimized further manually to flatten multiple paths, useless groups, and dramatically simplify paths the logos sprite was unnecessarily complex).

Happy to answer any questions on this!

### CODE REVIEW

**Comment by mfix22** [comment]
Thanks @majouji! 🙌

**Comment by mfix22** [comment]
Come on @all-contributors (:wink:) add @majouji for code

**Comment by mfix22** [comment]
@majouji what is this commit 69fd43bdcbf00f398e542228f29467b22391733f for? If you would like to make changes separate from optimizing _static_ PNGs and SVGs, can you please do that in a separate PR? 

Please move these last two commits into a new PR for review.

**Comment by majouji** [comment]
> @majouji what is this commit [69fd43b](https://github.com/carbon-app/carbon/commit/69fd43bdcbf00f398e542228f29467b22391733f) for? If you would like to make changes separate from optimizing _static_ PNGs and SVGs, can you please do that in a separate PR?
> 
> Please move these last two commits into a new PR for review.

Oh, my bad @mfix22 – meant to separate that one. This one is to prevent Safari on iOS from automatically zooming in when selecting an input field. Any input field with a computed `font-size` below 16px will cause this to happen. I’ll separate those.

**Comment by mfix22** [comment]
@majouji oh awesome! Sorry to make is a hassle, but I'd appreciate it as a separate PR. Want to keep this one super simple (just the static images). Really appreciate the help! 👍

**Comment by mfix22** [comment]
Please revert 32eddfdfe44ab255cd0998bfbcbca1d66d609261 as well — there are some bugs introduced in that commit.

**Comment by mfix22** [comment]
Screenshot 2019-10-11 12 02 40

Hey @majouji `open-source-companies-2.svg` looks a little funky after the optimization (see the NASA logo). Want to just keep that SVG as is?

**Comment by mfix22** [comment]
Thanks @majouji! 🙏

**Pull request merged**
