### PR TITLE
Add support for Copy As HTML

### LINKED ISSUE #1042: Copying to clipboard
Is there anyway to make it so you can export it as some equivalent of RTF so I can paste the code in with the colour coding? At the moment I use SublimeHighlight in Sublime Text to do this as it has a 'copy to clipboard as RTF'. If that were possible on Carbon it would be great.

### PR DESCRIPTION
**Pull request by Arriv9l**
I think **Copy As HTML** might has the same effect as **Copy As RTF**.
[copy-to-clipboard](https://github.com/sudodoki/copy-to-clipboard#api) now support copy with options, so I’ve already submitted a  [PR](https://github.com/mfix22/actionsack/pull/10) to [actionsack](https://github.com/mfix22/actionsack).
The effect is as follows, I’ve tested it by modifying node_modules\actionsack\dist\index.esm.js.

Close #1042

### CODE REVIEW

**Review by mfix22 — COMMENTED** [review]
@Arriv9l this is super cool! I'm happy to adopt this, but can we make sure the entire image gets copied? Not just what is within the text box? We want to include the background as well, for example.

**Comment by Arriv9l** [comment]
@mfix22  Sure. I'll give it a try.

**Comment by Arriv9l** [comment]
The final result is as follows:


- [x] Window Control: SVG is not supported, so I switched to emoji 🟠🟡🟢.
- [x] Background Color: has a limit of up to 6pt
- [ ] Background Image: not supported
- [ ] Drop Shadow: not supported

**Comment by mfix22** [comment]
@Arriv9l sorry if I wasn't clear in my previous statement. If we are to support this feature, it must match the live snippet exactly: it can't merely mimic it 😞 Sorry about that. 

I'm going to close this PR for now, but if you find a solution that allows for copying the HTML as is (styles and all) I will happily support it!

**Comment by Arriv9l** [comment]
Got it! 
For now, I’ve written a [script](https://greasyfork.org/en/scripts/422037-carbon-copy-as-html) to fulfill my requirements. 
If anyone has a similar need, feel free to try.

**Pull request closed without merging**
